const ACTIVE_PASSIVE_SKILL_NAMES = [
  '_3Faith',
  '_Argutus Vita_Telum',
  '_Biolo_Monster_List',
  '_ElementalMaster_spirit',
  '_Sorcerer_Elemental_Spirit',
  '_Meister_ABR_List',
  '_Meister_ABR_Warrior',
  '_Meister_ABR_Cannon',
  '_Meister_Quake',
  '_Meister_Rush',
  '_NightWatch_Aiming Count',
  '_Religio_Benedictum',
  '_Trouvere_Troubadour_ignore_res_mres',
  '_Trouvere_Troubadour_pAtk_sMatk',
  '_SoulAscetic_Blessing',
  '_Charm_Fire',
  '_Charm_Earth',
  '_Charm_Ice',
  '_Charm_Wind',
  '_SkyEmperor_Rising_Sun',
  '_SkyEmperor_Rising_Moon',
  '_Debuf_Sonic_Brand',
  'Talisman of Five Elements',
  'Totem of Tutelary',
  '16th Night',
  'Abyss Slayer',
  'Acid Demonstration',
  'Adrenaline Rush',
  'Sky Mastery',
  'War Book Mastery',
  'Advanced Book',
  'Advanced Katar Mastery',
  'Arclouse Dash',
  'Ardor',
  'Competentia',
  'Argutus Telum',
  'Argutus Vita',
  'Asir Runestone',
  'Assumptio',
  'Astral Strike',
  'Attack Stance',
  'Aura Blade',
  'Nature Friendly',
  'Auto Guard',
  'Auto Spell',
  'Axe Mastery',
  'Bash',
  'Basilica',
  'Beast Bane',
  'Benedictum',
  'Bio Cannibalize',
  'Blessing of Moon',
  'Blessing of Star',
  'Blessing of Sun',
  'Break Through',
  'Bunch of Shrimp',
  'Calamity Gale',
  'Camouflage',
  'Cantocandidus',
  'Cart Remodeling',
  'Cart Weight',
  'Cavalier Mastery',
  'Chain Action',
  'Charm',
  'Circling Nature',
  'Clementia',
  'Climax',
  'Cloaking Exceed',
  'Comet Amp',
  'Crazy Uproar',
  'Cross Wound',
  'Current HP',
  'Current SP',
  'Dagger & Bow Mastery',
  'Dagger Throwing Practice',
  'Dance With Wug',
  'Dancing Lesson',
  'Death Bound',
  'Demon Bane',
  'Distorted Crescent',
  'Divine Protection',
  'Divulio',
  'Dodge',
  'Double Attack',
  'Dragon Howling',
  'Dragon Training',
  'Dragonic Aura',
  'Dragonology',
  'Elemental Spirit Mastery',
  'Enchant Blade',
  'Enchant Deadly Poison',
  'Enchanting Shadow',
  'Expiatio',
  'Fairy Soul',
  'Falcon Soul',
  'Golem Soul',
  'Shadow Soul',
  'Faith',
  'Falcon Eyes',
  'Fear Breeze',
  'Fidus Animus',
  'Fire Earth Research',
  'Foresight',
  'Frash Shrimp',
  'Freezing Spell',
  'Frost Weapon',
  'Fusion of Sun, Moon and Star',
  'Geffenia Nocturne',
  'Gentle Touch - Alive',
  'Gentle Touch - Opposite',
  'Grand Judgement',
  'Gunslinger Mine',
  'Happy Break',
  'Heal',
  'Hiding',
  'Hilt Binding',
  'Holy Shield',
  'Illusion - Bewitch',
  'Illusion - Death',
  'Illusion - Shadow',
  'Illusion - Shock',
  'Impositio Manus',
  'Improve Concentration',
  'Improve Dodge',
  'Increase HP Recovery',
  'Increase SP Recovery',
  'Indulge',
  'Inspiration',
  'Intimidate',
  'Iron Hand',
  'Kaahi',
  'Katar Mastery',
  'Kiling Cloud',
  'Knowledge of Sun Moon and Star',
  'Knowledge of Sun, Moon and Star',
  'Kyrie Eleison',
  'Land Protector',
  'Laudaagnus',
  'Learning Potion',
  'Lefthand Mastery',
  'Lesson',
  'Lightning Loader',
  'Lunar Luminance',
  'Lux Anima Runestone',
  'Mace & Book Mastery',
  'Mace Mastery',
  'Madogear License',
  'Maelstrom',
  'Magic Book Mastery',
  'Magic Sword Mastery',
  'Magnificat',
  'Main Ranger',
  'March of Prontera',
  'Meditation',
  'Meow Meow',
  'Moonlight Fantasy',
  'Moonlight Serenade',
  'Musical Lesson',
  'Mystic Symphony',
  'Neutral Barrier',
  'New Poison Research',
  'Ninja Aura',
  'Ninja Mastery',
  'Offertorium',
  'On Magogear',
  'Peaceful Break',
  'Piety',
  'Plagiarism',
  'Platinum Altar',
  'Poisonous Weapon',
  'Potent Venom',
  'Power Maximize',
  'Power of Flock',
  'Power of Land',
  'Power of Life',
  'Power of Sea',
  'Power Thrust',
  'Power',
  'Self Study Tactics',
  'Self Study Sorcery',
  'Mystical Creature Mastery',
  'Commune with Chulho',
  'Commune with Hyunrok',
  'Colors of Hynrok',
  'Presens Acies',
  'Preserve',
  'Procella',
  'Pure Soul',
  'Pyroclastic',
  'Radius',
  'Recognized Spell',
  'Released',
  'Religio',
  'Reproduce',
  'Rhapsody of Mineworker',
  'Ride Dragon',
  'Ride Peco',
  'Righthand Mastery',
  'Rising Dragon',
  'Run',
  'Rune Mastery',
  'Rush To Windmill',
  'Safety Wall',
  'Scratch',

  'Seismic Weapon',
  'Serenade of Jawaii',
  'Serpens',
  'Seven Wind',
  'Shadow Exceed',
  'Shadow Formation',
  'Shadow Sense',
  'Shadow Spell',
  'Shadow Warrior',
  'Shadow Wound',
  'Shield Mastery',
  'Shield Spell',
  'Silvervine Root Twist',
  'Single Action',
  'Skin Tempering',
  'Snake Eyes',
  'Snatcher',
  'PFI',
  'Intensive Aim',
  'Grenade Fragment',
  'Debuff_Spore Explosion',
  'Solar Luminance',
  'Solar Stance',
  'Song Of Mana',
  'Research Report',
  'Soul Cutter',
  'Soul Drain',
  'Soul',
  'Spear & Sword Mastery',
  'Spear Dynamo',
  'Spear Mastery',
  'Spear Quicken',
  'Spell Enchanting',
  'Spin Count',
  'Sprit Of Life',
  'Stage Manner',
  'Steel Crow',
  'Stellar Luminance',
  'Stellar Stance',
  'Striking',
  'Strip Shadow',
  'Swing Dance',
  'Sword Mastery',
  'Terramotus',
  'Grenade Mastery',
  'Total Soul',
  'Total Spirit',
  'Transcendence',
  'Trap Research',
  'Turisus Runestone',
  'Two Hand Defending',
  'Two hand Quicken',
  'Two hand Staff Mastery',
  'Hidden Card',
  'Two-Handed Sword Mastery',
  'Venom Impression',
  'Vigor condensation',
  'Vigor Explosion',
  'Weapon Blocking',
  'Weapon Perfection',
  'Weaponry Research',
  'Sincere Faith',
  'Firm Faith',
  'Powerful Faith',
  'Will of Faith',
  'Wind Walk',
  'Wooden Fairy',
  'Wounding Shot',
  'Wrath of',
  'Empty Shadow',
  'Wug Rider',
  "Bragi's Poem",
  "Frigg's Song",
  "Lerad's Dew",
  "Odin's Power",
  "Owl's Eye",
  "Vulture's Eye",
  'Talisman Mastery',
  'Soul Mastery',
] as const;

export const OFFENSIVE_SKILL_NAMES = [
  'Abyss Dagger',
  'Acid Bomb',
  'Dancing Knife',
  'Acid Terror',
  'Acidified Zone Earth',
  'Acidified Zone Fire',
  'Acidified Zone Water',
  'Acidified Zone Wind',
  'Adoramus',
  'All Bloom',
  'Aimed Bolt',
  'Anti-Material Blast',
  'Arbitrium',
  'Arm Cannon',
  'Arrow Shower',
  'Arrow Storm',
  'Arrow Vulcan',
  'Axe Boomerang',
  'Axe Stomp',
  'Axe Tornado',
  'Kunai - Nightmare',
  'Imperial Cross',
  'Energy Cannonade',
  'Mystery Powder',
  'Wild Walk',
  'All in the Sky',
  'Dark Dragon - Nightmare',
  'Hyunrok Spirit Power',
  'Back Stab',
  'Banishing Point',
  'Basic Grenade',
  'Bionic Pharmacy',
  'Blaze Kick',
  'Blitz Beat',
  'Bomb Cluster',
  'Bowling Bash',
  'Brandish Spear',
  'Burst Attack',
  'Cannon Spear',
  'Cart Boost',
  'Cart Cannon',
  'Cart Revolution',
  'Cart Termination',
  'Cart Tornado',
  'Catnip Meteor',
  'Chain Combo',
  'Chain Crush Combo',
  'Chain Lightning',
  'Chain Reaction Shot',
  'Chattering',
  'Clashing Spiral',
  'Claymore Trap',
  'Cold Bolt',
  'Cold Slower',
  'Combo Finish',
  'Comet',
  'Conflagration',
  'Counter Slash',
  'Crazy Weed',
  'Crescive Bolt',
  'cri_race_demon',
  'cri_race_dragon',
  'cri_race_fish',
  'cri_race_insect',
  'cri_race_undead',
  'Crimson Arrow',
  'Crimson Marker',
  'Crimson Rock',
  'Cross Impact',
  'Cross Rain',
  'Cross Ripper Slasher',
  'Cross Slash',
  'Curse Explosion',
  'Dark Claw',
  'Dark Illusion',
  'Dart Arrow',
  'Deft Stab',
  'Desperado',
  'Diamond Dust',
  'Diamond Storm',
  'dmg__Lucifer Morocc',
  'Double Strafe',
  'Dragon Breath - WATER',
  'Dragon Breath',
  'Dragon Combo',
  'Dragon Tail',
  'Drain Life',
  'Duple Light',
  'Earth Drive',
  'Earth Grave',
  'Earth Shaker',
  'Earth Spike',
  'Earth Strain',
  'Elemental Buster',
  'Envenom',
  'Esma',
  'Espa',
  'Eswhoo',
  'Eternal Slash',
  'Evil Soul Curse',
  'Exploding Dragon',
  'Explosion Blaster',
  'Fallen Empire',
  'Falling Stars',
  'Fatal Manace',
  'Fatal Shadow Claw',
  'Feint Bomb',
  'Finger Offensive',
  'Fire Ball',
  'Fire Bolt',
  'Fire Dance',
  'Fire Pillar',
  'Fire Rain',
  'Firewall',
  'First Brand',
  'First Wind',
  'Fist Spell',
  'Flame Launcher',
  'Flaming Petals',
  'Flash Combo',
  'Flash Kick',
  'Floral Flare Road',
  'Focused Arrow Strike',
  'Framen',
  'Freezing Spear',
  'Frenzy Shot',
  'From the Abyss',
  'Frost Misty',
  'Frost Nova',
  'Frozen Slash',
  'Full Blast',
  'Full Moon Kick',
  'Gale Storm',
  'Genesis Ray',
  'Gloria Domini',
  'Grand Cross',
  'Gravitational Field',
  'Great Echo',
  'Grenade Dropping',
  'Grimtooth',
  'Hack and Slasher',
  'Hasty Fire in the Hole',
  'Hell Gate',
  'Hell Inferno',
  'Hell Plant',
  'Hesperus Lit',
  'Hiss',
  'Holy Cross',
  'Holy Light',
  'Hot Barrel',
  'Howling Mine',
  'Hundred Spears',
  'Ignition Break',
  'Impact Crater',
  'Infiltration',
  'Intensification',
  'Jack Frost',
  'Judex',
  'Jupitel Thunder',
  'Killing Cloud',
  'Knuckle Arrow',
  'Knuckle Boost',
  'Kunai Explosion',
  'Kunai Splash',
  'Land Mine',
  'Lava Flow',
  'Lightening Bolt',
  'Lightning Land',
  'Lightning Ride',
  'Lion Howling',
  'Lord of Vermilion',
  'Lucky Cast',
  'Lunatic Carrot Beat',
  'Madness Crusher',
  'Magazine for One',
  'Magnum Break',
  'Magnus Exorcismus',
  'Mammonite',
  'Mandragora Howling',
  'Masquerade-Enervation',
  'Masquerade-Groomy',
  'Masquerade-Weakness',
  'Mass Spiral',
  'Massive Flame Blaster',
  'Metalic Sound',
  'Meteor Assault',
  'Meteor Storm',
  'Midnight Fallen',
  'Mission Bombard',
  'Moon Slasher',
  'Musical Strike',
  'Mystery Illusion',
  'Mystical Amplification',
  'Napalm Beat',
  'Napalm Vulcan',
  'New Moon Kick',
  'No Limits',
  'Nuckle Boost',
  'Nyang Grass',
  'Oleum Sanctum',
  'Omega Abyss Strike',
  'Only One Bullet',
  'Oratio',
  'Over Brand',
  'Overslash',
  'Petitio',
  'Picky Peck',
  'Pierce',
  'Pile Bunker',
  'Poison Burst',
  'Power Absorb',
  'Power Swing',
  'Psychic Wave',
  'Quick Draw Shot',
  'Raid',
  'Rain of Crystal',
  'Rampage Blast',
  'Reverberation',
  'Rhythm Shooting',
  'Rock Down',
  'Rolling Cutter',
  'Round Trip',
  'Rush Quake',
  'Savage Impact',
  'Scar of Tarou',
  'Second Faith',
  'Second Flame',
  'Second Judgement',
  'Servant Weapon',
  'Severe Rainstorm',
  'Shadow Stab',
  'Shatter Storm',
  'Shield Boomerang',
  'Shield Chain',
  'Shield Press',
  'Shield Shooting',
  'Sightless Mind',
  'Silvervine Stem Spear',
  'Sky Blow',
  'Slinging Arrow',
  'Slug Shot',
  'Snow Flake Draft',
  'Solar Explosion',
  'Sonic Blow',
  'Sonic Wave',
  'Soul Destroyer',
  'Soul Expansion',
  'Soul Harvest',
  'Soul Strike',
  'Soul Vulcan Strike',
  'Spiral Shooting',
  'Spirit of Savage',
  'Spore Explosion',
  'Spread Shot',
  'Sprit Of Savage',
  'Storm Blast',
  'Storm Cannon',
  'Storm Gust',
  'Storm Slash',
  'Stratum Tremor',
  'Suicidal Destruction',
  'Swirling Petal',
  'Tasty Shrimp Party',
  'Terra Drive',
  'Tetra Vortex',
  'The Vigilante at Night',
  'Third Consecration',
  'Third Flame Bomb',
  'Third Punish',
  'Throw Huuma Shuriken',
  'Throw Kunai',
  'Thunderstorm',
  'Tiger Cannon',
  'Tornado Axe',
  'Tornado Storm',
  'Triangle Shot',
  'Turn Undead',
  'Unlucky Rush',
  'Urgent Escape',
  'Vanishing Buster',
  'Varetyr Spear',
  'Venom Swamp',
  'Vulcan Arm',
  'Warmer',
  'Water Insignia',
  'Wild Fire',
  'Wild Shot',
  'Wind Blade',
  'Wind Cutter',
  'Wug Strike',
  "Deep Blind Trap",
  "Flame Trap",
  "God's Hammer",
  "Heaven's Drive",
  "Rich's Coin",
  "Solid Trap",
  "Sound Blend",
  "Swift Trap",
  "Switf Trap",

  // 4th in the future
  "Abyss Square",
  "Activation Attack Machine",
  "Chulho Sonic Claw",
  "Cold Blooded Cannon",
  "Crystal Impact",
  "Darkening Cannon",
  "Dawn Break",
  "Destructive Hurricane",
  "Double Bowling Bash",
  "Dragonic Breath",
  "Effligo",
  "Exorcism of Malicious Soul",
  "Explosive Powder",
  "Flamen",
  "Golden Dragon Cannon",
  "Ground Gravitation",
  "Hawk Boomerang",
  "Hawk Rush",
  "Hell's Drive",
  "Hogogong Strike",
  "Howling of Chulho",
  "Huuma Shuriken - Construct",
  "Huuma Shuriken - Grasp",
  "Hyunrok Breeze",
  "Hyunrok Cannon",
  "Jack Frost Nova",
  "Jupitel Thunderstorm",
  "Kunai - Distortion",
  "Kunai - Refraction",
  "Kunai - Rotation",
  "Mayhemic Thorns",
  "Mega Sonic Blow",
  "Metallic Fury",
  "Meteor Storm Buster",
  "Midnight Kick",
  "Mighty Smash",
  "Napalm Vulcan Strike",
  "Noon Blast",
  "Phantom Menace",
  "Rapid Smiting",
  "Red Flame Cannon",
  "Rising Sun",
  "Rock Down Arrow",
  "Rose Blossom",
  "Shadow Dance",
  "Shadow Flash",
  "Shadow Hunting",
  "Shield Chain Rush",
  "Spark Blaster",
  "Spiral Pierce Max",
  "Star Cannon",
  "Sunset Blast",
  "Talisman of Black Tortoise",
  "Talisman of Blue Dragon",
  "Talisman of Four Bearing God",
  "Talisman of Red Phoenix",
  "Talisman of Soul Stealing",
  "Talisman of White Tiger",
  "Thundering Cannon",
  "Triple Laser",
  "Twinkling Galaxy",
  "Violent Quake",
  "Warg Strike",

  'Abyss Flame',
  'Dust Explosion',
  'Radiant Spear',
  'Star Light Kick',
  'Sky Sun',
  'Sky Moon',
  'Psychic Stream',
  'Divinus Flos',
  'Pneumaticus Procella',
  'Chulho Battering',
  'Blazing Flame Blast',
  'Rhythmical Wave',
  'Powerful Swing',
  'Rush Strike',
  'Dragonic Pierce',
  'Soul Gathering',
] as const;

const dup = [];
for (const s of ACTIVE_PASSIVE_SKILL_NAMES) {
  if (OFFENSIVE_SKILL_NAMES.includes(s as any)) {
    dup.push(s);
  }
}

if (dup.length > 0) console.log('skillname_dupplicates', dup);

export type SKILL_NAME = (typeof ACTIVE_PASSIVE_SKILL_NAMES)[number] | (typeof OFFENSIVE_SKILL_NAMES)[number];
